### ISSUE TITLE
Flickering of delete group confirmation popup.

### ISSUE THREAD

**Issue by Hashir311** [Hashir311/SplitIT#1]
The group deletion popup flickers at the center of the screen which makes it difficult to delete a group by the user that created it.

**Comment by nishant19dwivedi** [comment]
Hi @Hashir311 
I would love to contribute  to this issue for Hacktoberfest! Could you please assign it to me?
And can you also provide with the steps to reproduce this bug.

**Comment by Hashir311** [comment]
yeah sure
after you set up the enviroment in the root directory move to SplitIT folder and launch the web app. create a super user if you need so. 
so the issue is encountered when a user has created a group and tries to delete it using the delete button on the dashboard. try testing by signing up multiple users. 
feel free to reach out if you sought any help.
PS: i am quite new to development so please ignore redundant and bad code. a lot of sections of the code are static and are under development.

**Comment by nishant19dwivedi** [comment]
Hi @Hashir311 , I have created a pull request for the fix, please review it .

You are doing great, don't worry you'll get better at it.
All the best for future

**Comment by Hashir311** [comment]
Hey @nishant19dwivedi,
Thank you for helping me out! I really appreciate your support and guidance.
Looking forward to collaborating more in the future!

**Comment by nishant19dwivedi** [comment]
Hey, @Hashir311 no problem at all! Glad I could help. Looking forward to working together again soon!
