### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by Hashir311** [Hashir311/SplitIT#10]
Create a custom 404 Page for the project

**Comment by swarupn17** [comment]
Hey @Hashir311 I can do this task. Please can you assign it to me.
Thanks!

**Comment by Hashir311** [comment]
Hi @swarupn17, thanks for reaching out! I wanted to let you know that the issue has already been addressed by another contributor, and I’ve merged their PR.
I’ll be raising more issues in the future, and I’d love for you to collaborate on those. Looking forward to working together!
