### ISSUE TITLE
No names of the members are displayed in the group

### ISSUE THREAD

**Issue by Jasneet-09** [Hashir311/SplitIT#27]
Currently, when a particular group is clicked in the application, the names of the members within the group are not visible. While the group members can be seen when adding an expense, it is difficult to track or manage group members directly from the group view itself. This causes confusion for users when they need to quickly check how many people are in the group or who the members are.

Possible solution: Add a member list display feature to the group view. This could be a simple section that lists all the group members with their names and possibly some additional details (e.g., email, role in the group). This enhancement would improve the user experience by making managing and understanding group compositions easier.

Could you please assign this issue to me? I’d be happy to submit a fix.

**Comment by Hashir311** [comment]
I have assigned you this issue, make sure that the section you add follows the overall theme. You may also move the `Add Member` button in that section.
