### ISSUE TITLE
E-mail id validation on the signup page.

### ISSUE THREAD

**Issue by Hashir311** [Hashir311/SplitIT#6]
There is no validation for email entered on the signup page. The validation should be done on the client side so to avoid server request.

**Comment by ragul1697** [comment]
Hi @Hashir311, Changing `input type='email'` on email input would add basic email validation on client side. But you can also add  validation using JavaScript.

**Comment by Hashir311** [comment]
Hey @ragul1697 , Thanks for pointing this out. Just fixed it.
